//! WebAssembly emission for the AVM2 JIT.
//!
//! For now this holds the plumbing seed: [`emit_add_module`] produces a tiny,
//! self-contained module so the whole pipeline can be exercised end-to-end
//! (emit → the browser's engine compiles it → call it). The real ABC → WASM
//! lowering (fixed-offset loads/stores into the frame's `state_ptr`, a
//! compile-time operand stack, structured control flow, and helper `call`s for
//! GC-aware ops) is built on top of these primitives.

use wasm_encoder::{
    CodeSection, ExportKind, ExportSection, Function, FunctionSection, Instruction, Module,
    TypeSection, ValType,
};

/// Emits a minimal module exporting `add(i32, i32) -> i32`.
///
/// This is the "hello world" of the emit → compile → call pipeline: it proves
/// the browser can compile our generated bytes and that we can call the result.
pub fn emit_add_module() -> Vec<u8> {
    let mut module = Module::new();

    // Type 0: (i32, i32) -> i32
    let mut types = TypeSection::new();
    types.ty().function([ValType::I32, ValType::I32], [ValType::I32]);
    module.section(&types);

    // One function of type 0.
    let mut functions = FunctionSection::new();
    functions.function(0);
    module.section(&functions);

    // Export it as "add".
    let mut exports = ExportSection::new();
    exports.export("add", ExportKind::Func, 0);
    module.section(&exports);

    // Body: local.get 0; local.get 1; i32.add; end.
    let mut code = CodeSection::new();
    let mut f = Function::new([]);
    f.instruction(&Instruction::LocalGet(0));
    f.instruction(&Instruction::LocalGet(1));
    f.instruction(&Instruction::I32Add);
    f.instruction(&Instruction::End);
    code.function(&f);
    module.section(&code);

    module.finish()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn emits_a_wasm_binary() {
        let bytes = emit_add_module();
        // WASM magic + version.
        assert_eq!(&bytes[0..4], b"\0asm");
        assert_eq!(&bytes[4..8], &[1, 0, 0, 0]);
        assert!(bytes.len() > 8);
    }
}

/// In-browser end-to-end test: hand the emitted bytes to the engine, instantiate,
/// and call. Run with `wasm-pack test --headless --firefox -p ruffle_avm2_jit`.
#[cfg(all(test, target_arch = "wasm32"))]
mod wasm_tests {
    use super::*;
    use wasm_bindgen::{JsCast, JsValue};
    use wasm_bindgen_test::*;

    wasm_bindgen_test_configure!(run_in_browser);

    #[wasm_bindgen_test]
    fn browser_compiles_and_runs_emitted_add() {
        let bytes = emit_add_module();
        let arr = js_sys::Uint8Array::from(bytes.as_slice());
        let module = js_sys::WebAssembly::Module::new(&arr.into()).expect("browser compiles module");
        let imports = js_sys::Object::new();
        let instance =
            js_sys::WebAssembly::Instance::new(&module, &imports).expect("instantiate");
        let add = js_sys::Reflect::get(&instance.exports(), &JsValue::from_str("add"))
            .unwrap()
            .dyn_into::<js_sys::Function>()
            .unwrap();
        let result = add
            .call2(&JsValue::NULL, &JsValue::from(2), &JsValue::from(3))
            .unwrap();
        assert_eq!(result.as_f64().unwrap() as i32, 5);
    }
}
